[package]
name = "ddbug"
version = "0.1.0"
authors = ["Philip Craig <philipjcraig@gmail.com>"]

[dependencies]
env_logger = "0.3.5"
getopts = "0.2.14"
gimli = { git = "https://github.com/gimli-rs/gimli", rev = "d482c1f" }
log = "0.3.6"
memmap = "0.4.0"
panopticon = { git = "https://github.com/philipc/panopticon", branch = "ddbug" }
xmas-elf = "0.3"
