[package]
name = "ddbug"
version = "0.1.0"
authors = ["Philip Craig <philipjcraig@gmail.com>"]
description = "Display debugging information"
repository = "https://github.com/philipc/ddbug"
readme = "README.md"
keywords = ["debug", "DWARF", "PDB"]
categories = ["development-tools::debugging"]
license = "Apache-2.0/MIT"

[dependencies]
env_logger = "0.3.5"
getopts = "0.2.14"
gimli = "0.14.0"
goblin = "0.0.10"
log = "0.3.6"
memmap = "0.4.0"
pdb = "0.1.5"
