[package]
name = "ddbug"
version = "0.1.0"
authors = ["Philip Craig <philipjcraig@gmail.com>"]

[dependencies]
env_logger = "0.3.5"
getopts = "0.2.14"
gimli = { git = "https://github.com/gimli-rs/gimli", rev = "b2db9c2a90b3447190e2e02eb27e6bf1da16183c" }
goblin = "0.0.10"
log = "0.3.6"
memmap = "0.4.0"
panopticon-core = { git = "https://github.com/das-labor/panopticon" }
panopticon-amd64 = { git = "https://github.com/das-labor/panopticon" }
pdb = "0.1.5"

[dev-dependencies]
rand = "0.3.15"
