[package]
name = "ddbug"
version = "0.1.0"
authors = ["Philip Craig <philipjcraig@gmail.com>"]

[dependencies]
env_logger = "0.3.5"
getopts = "0.2.14"
gimli = { git = "https://github.com/gimli-rs/gimli", rev = "fdd6feb5b652d69428db488b3854b4f94b0d8692" }
log = "0.3.6"
memmap = "0.4.0"
panopticon = { git = "https://github.com/philipc/panopticon", branch = "ddbug" }
pdb = "0.1.1"
xmas-elf = "0.5.0"

[dev-dependencies]
rand = "0.3.15"
