[package]
name = "ddbug_parser"
version = "0.2.0"
authors = ["Philip Craig <philipjcraig@gmail.com>"]
description = "Unified debug information parser"
repository = "https://github.com/philipc/ddbug"
keywords = ["debug", "DWARF", "PDB"]
categories = ["development-tools::debugging"]
license = "Apache-2.0/MIT"
edition = "2018"

[dependencies]
fnv = "1.0"
gimli = "0.19"
log = "0.4"
memmap = "0.7"
moria = { git = "https://github.com/gimli-rs/moria", rev = "9f944d62a092f057169e1dce74937d50afc53c89" }
#moria = { path = "../../moria" }
object = "0.14"
#object = { version = "0.17", path = "../../object" }
typed-arena = "1.3"

[features]
default = []
